### PR TITLE
Update contributors.json with personal info

### PR DESCRIPTION
**Pull request by frclba**

### CODE REVIEW

**Review by rabbitwerks — APPROVED** [review]
lgtm

**Review by ewenjo — APPROVED** [review]
I don't think I have write access

**Review by spiray — APPROVED** [review]

**Comment by spiray** [comment]
My approval was worthless ;)

**Review by joshuaferr1s — APPROVED** [review]
looks good

**Comment by frclba** [comment]
Thanks!!!

**Pull request merged**
