### PR TITLE
Add my info

### PR DESCRIPTION
**Pull request by derkarol**
So after solving: forking, committing with being in correct dir of the forked repo not cloned upstream of w3cj, here is my PR...I hope

### CODE REVIEW

**Review by westborn — APPROVED** [review]
All good

**Review by w3cj — CHANGES_REQUESTED** [review]
I've added the prettier formatter to the repo. Please pull the latest changes and run prettier.

```sh
git remote add coding-garden https://github.com/CodingGardenCommunity/contributors.git
git pull coding-garden master
npm install
npm run format
```

You may need to fix merge conflicts before running `npm run format`

**Comment by derkarol** [comment]
is it ok, now?

**Comment by spiray** [comment]
@derkarol No, We made a bunch of changes. I would recommend starting over and pulling the master branch and then copy somebody's entry and change the details to yours. Once that is done, execute npm run format and commit. Let me know if you have trouble.

**Comment by derkarol** [comment]
I did new FORK the master branch and add my info as well run format commit. All on new rfork so I close this, @spiray thanks for some hint!

**Pull request closed without merging**
