### PR TITLE
:tada: Details Contributors List

### PR DESCRIPTION
**Pull request by PranjalAgni**
Add my details :)

### CODE REVIEW

**Comment by snordmann** [comment]
Could you please also fill out your information here: <https://docs.google.com/spreadsheets/d/1Lcsp-oB49tILBhLufn_fNOh32zCHdDWO-9ie7ORyUnc/edit#gid=0>?
This is what we are actually using to assign the teams on Discord and GitHub.

**Review by rabbitwerks — APPROVED** [review]
looks good

**Comment by PranjalAgni** [comment]
Filled the details in the sheet 💻

**Review by rabbitwerks — APPROVED** [review]
Looks good!

**Comment by spiray** [comment]
@PranjalAgni  Can you re-commit with resolved conflicts?

**Comment by spiray** [comment]
Closing this PR pending the merge conflict resolution by @PranjalAgni.

**Pull request closed without merging**
