### PR TITLE
Added my record

### PR DESCRIPTION
**Pull request by spiray**
Added my record to the JSON file!

### CODE REVIEW

**Review by derkarol — APPROVED** [review]

**Review by derkarol — APPROVED** [review]
But i think your image link may end faster on this id .../26689583

**Review by westborn — APPROVED** [review]
All good

**Review by w3cj — CHANGES_REQUESTED** [review]
Please do not update the spacing / format of the rest of the file. Currently using a 2 space tab.

When you view the changes to the file on github, you should only see your added information as the changed lines.

Update and re-submit.

**Comment by w3cj** [comment]
I've added the prettier formatter to the repo. Please pull the latest changes and run prettier.

```sh
git remote add coding-garden https://github.com/CodingGardenCommunity/contributors.git
git pull coding-garden master
npm install
npm run format
```

You may need to fix merge conflicts before running `npm run format`

**Comment by spiray** [comment]
Thanks @w3cj! I made the requested changes!

**Review by rabbitwerks — APPROVED** [review]
corrections look good.

**Review by w3cj — APPROVED** [review]

**Pull request merged**
